#pragma once
#ifndef H_MLN_DB_VERSION_H
#define H_MLN_DB_VERSION_H

#define MLN_DB_VERSION_MAJOR 0
#define MLN_DB_VERSION_MINOR 8
#define MLN_DB_VERSION_PATCH 0
#define MLN_DB_VERSION_TWEAK 0

#endif //H_MLN_DB_VERSION_H