#pragma once
#ifndef H_MLN_DB_COMMANDS_H
#define H_MLN_DB_COMMANDS_H

#include "commands/ping.h"
#include "commands/pong.h"
#include "commands/thinking.h"
#include "commands/bot_info.h"
#include "commands/file.h"
#include "commands/pm.h"
#include "commands/msgs_get.h"
#include "commands/channel_create.h"
#include "commands/msg_error.h"
#include "commands/image.h"
#include "commands/blep.h"
#include "commands/show.h"
#include "commands/add_role.h"
#include "commands/button.h"
#include "commands/button2.h"
#include "commands/math.h"
#include "commands/pring.h"
#include "commands/select.h"
#include "commands/select2.h"
#include "commands/select3.h"
#include "commands/dialog.h"
#include "commands/add_emoji.h"
#include "commands/avatar.h"
#include "commands/co_button.h"
#include "commands/help.h"

#endif //H_MLN_DB_COMMANDS_H